---@class PackSpec
---@field [1] string              -- url
---@field name string             -- parsed from url
---@field modname string?         -- for plugin requires
---@field enabled boolean?
---@field lazy boolean?
---@field event string[]|nil
---@field ft string[]|nil
---@field keys KeyConfig[]|nil
---@field cmd string[]|nil
---@field deps PackSpec[]?             -- dependencies
---@field opts table|function|nil
---@field _opts table?            -- resolved opts
---@field init function?
---@field config function?
---@field pfile string            -- file containing the plugin
