return {
  'SmiteshP/nvim-navic',
  init = function()
    vim.g.navic_silence = true
  end,

  opts = {
    separator = ' ',
    highlight = true,
    depth_limit = 5,
    icons = {
      Array         = ' ',
      Boolean       = '󰨙 ',
      Class         = ' ',
      Color         = ' ',
      Control       = ' ',
      Collapsed     = ' ',
      Constant      = '󰏿 ',
      Constructor   = ' ',
      Enum          = ' ',
      EnumMember    = ' ',
      Event         = ' ',
      Field         = ' ',
      File          = ' ',
      Folder        = ' ',
      Function      = '󰊕 ',
      Interface     = ' ',
      Key           = ' ',
      Keyword       = ' ',
      Method        = '󰊕 ',
      Module        = ' ',
      Namespace     = '󰦮 ',
      Null          = ' ',
      Number        = '󰎠 ',
      Object        = ' ',
      Operator      = ' ',
      Package       = ' ',
      Property      = ' ',
      Reference     = ' ',
      Snippet       = '󱄽 ',
      String        = ' ',
      Struct        = '󰆼 ',
      Supermaven    = ' ',
      Text          = ' ',
      TypeParameter = ' ',
      Unit          = ' ',
      Value         = ' ',
      Variable      = '󰀫 ',
    },
    lazy_update_context = true,
  }
}
